"""Add Coupon Table

Revision ID: db5399354d89
Revises: 049ad6b3c07e
Create Date: 2024-04-29 13:10:01.491129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5399354d89'
down_revision: Union[str, None] = '049ad6b3c07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('logged', sa.Boolean(), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('uses_total', sa.Integer(), nullable=False),
    sa.Column('uses_customer', sa.String(length=11), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('skus', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('collections', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
